"""Python SDK for SensWear hardware."""

from .client import DiscoveredDevice, SenswearClient
from .exceptions import (
    DeviceNotFoundError,
    NotConnectedError,
    ProtocolError,
    SenswearDependencyError,
    SenswearError,
)
from .modules import (
    ActivitySample,
    ActivityTransition,
    BatteryGaugeState,
    BatteryLevel,
    BatteryLevelStatus,
    ChargeLevel,
    ChargeState,
    ChargerState,
    CurrentTime,
    GestureSample,
    GyroscopeSample,
    HapticFrame,
    HapticPattern,
    ImuActivity,
    ImuGesture,
    LedColor,
    LinearAccelerationSample,
    LocalTimeInformation,
    PowerSourceState,
    PpgSample,
    QuaternionSample,
    RawTouchSample,
    ReferenceTimeInformation,
    TemperatureMeasurement,
    TemperatureSample,
    TemperatureType,
    TouchGesture,
    TouchGestureSample,
    TouchState,
)

__all__ = [
    "ActivitySample",
    "ActivityTransition",
    "BatteryGaugeState",
    "BatteryLevel",
    "BatteryLevelStatus",
    "ChargeLevel",
    "ChargeState",
    "ChargerState",
    "CurrentTime",
    "DeviceNotFoundError",
    "DiscoveredDevice",
    "GestureSample",
    "GyroscopeSample",
    "HapticFrame",
    "HapticPattern",
    "ImuActivity",
    "ImuGesture",
    "LedColor",
    "LinearAccelerationSample",
    "LocalTimeInformation",
    "NotConnectedError",
    "PowerSourceState",
    "PpgSample",
    "ProtocolError",
    "QuaternionSample",
    "RawTouchSample",
    "ReferenceTimeInformation",
    "SenswearClient",
    "SenswearDependencyError",
    "SenswearError",
    "TemperatureMeasurement",
    "TemperatureSample",
    "TemperatureType",
    "TouchGesture",
    "TouchGestureSample",
    "TouchState",
]

__version__ = "0.2.0"
